### ISSUE TITLE
The latest development build 9593260 has made Nog mostly unusable

### ISSUE THREAD

**Issue by keepitsane** [TimUntersberger/nog#175]
**Version (which release did you use?)**
9593260

The performance and stability of this version has seriously regressed to the point that for me to continue using Nog I needed to roll back to the previous version. 

- Switching between workspaces has become extremely slow and windows are disappearing
- Things from my config files such as bar customization's and rules are not being respected by Nog
- The Windows Taskbar is no longer being hidden on one of my monitors. Trying to toggle the taskbar on and off causes Nog to completely freeze up and not listen to any inputs (think might be deadlock)
- Deadlocks and freezes basically instantly or shortly after starting Nog
- Trying to quit Nog using shortcut when it is deadlocked doesn't work. Even trying to exit Nog by right clicking the Nog icon in the notification area and selecting Exit simply removes the icon, but doesn't actually quit or close Nog.
- In one case Nog completely froze up my entire computer and had to do a hard shutdown

Looking at the log files doesn't seem to show anything out of the ordinary. Nog just basically stops listening to all inputs and freezes up, one thing I noticed however is that the clock in the appbar still works. So I don't think Nog is crashes, but rather it just stops listening to keyboard inputs for some reason.

I have only been using it for 30 minutes today so far, and was forced to roll back down. The version I had been using before updating today was b73390b. My suggestion would be to potential rollback the development branch til the latest merged in branches are a bit more stable. I can test out some of the other branches to see if I encounter the same issues if that would be helpful.

Please let me know if there is anything specific you want me to test or something to look for in the log files. I can build the current version this weekend and mess around to see if I can figure anything out.

**Comment by TimUntersberger** [comment]
# Switching between workspaces has become extremely slow and windows are disappearing

Fixed the disappearing problem, but can't reproduce the slowness.

# Things from my config files such as bar customization's and rules are not being respected by Nog

Bar customization should be fixed, if you are talking about `font_size`.

Rules are working fine for me. Can you show me an example rule that doesn't work for you?

# The Windows Taskbar is no longer being hidden on one of my monitors

Fixed.

# Trying to toggle the taskbar on and off causes Nog to completely freeze up and not listen to any inputs (think might be deadlock)

I can't reproduce this. I tried changing the config manually and saving the file and using a `toggle_config` keybinding.

# Deadlocks and freezes basically instantly or shortly after starting Nog

Can't reproduce this either.

# Trying to quit Nog using shortcut when it is deadlocked doesn't work. Even trying to exit Nog by right clicking the Nog icon in the notification area and selecting Exit simply removes the icon, but doesn't actually quit or close Nog.

Did this work before? This shouldn't be possible.

# In one case Nog completely froze up my entire computer and had to do a hard shutdown

This seems weird. Maybe the CPU Usage skyrocketed? Did you try spawning the task manager?

**Comment by keepitsane** [comment]
> Bar customization should be fixed, if you are talking about font_size.

Seems that bar color is still broken.

> I can't reproduce this. I tried changing the config manually and saving the file and using a toggle_config keybinding.

Don't seem to be having the problem, but will continue to monitor if it pops back up.


> Trying to quit Nog using shortcut when it is deadlocked doesn't work. Even trying to exit Nog by right clicking the Nog icon in > the notification area and selecting Exit simply removes the icon, but doesn't actually quit or close Nog.
> Did this work before? This shouldn't be possible.

I think the issue with this maybe when a deadlock happens, it is still registering any keybindings that are being hit. So Nog is trying to processes all the keybindings in the queue in order and not giving priority to the quit keybinding or exit command. Potentially it might help to have a dedicated thread for only exit/quit commands?

> This seems weird. Maybe the CPU Usage skyrocketed? Did you try spawning the task manager?

I did CPU was at 100% with Nog using the most and then the task manager stopped responding as well. Potential could have just been a one off thing as in all my time using Nog so far that is the first time it ever happened. But Ill keep on the watch if it happens again.

Overall, this build seems to be much better and thanks for the quick reply and fixes. I'll continue to test and will keep this issue open for the time being. I think it is probably safe to merge the latest cross-platform branch back into development.

**Comment by keepitsane** [comment]
Clicking on the workspaces number in the appbar when two workspaces are active seems to cause issues if other empty workspaces are registered to that monitor. For example on one of my monitors I have assigned worspace 4, 5, and 6. If I have windows open on workspace 5 and 6, and I click on with my cursor to switch to workspace 5 it opens workspace 4 instead. Clicking on the workspace 5 a second time switches to the correct workspace. 

Should I continue to report this issue under this issue for the time being, or resume opening individual issue posts?

**Comment by keepitsane** [comment]
Going to move the above issue into its own thread as most of the issues from original post have been solved.
